version: '3.8'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      # The DATABASE_URL will be used by your Flask app.
      - DATABASE_URL=postgresql://postgres:postgres@db/my_author_website_db
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: my_author_website_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
